In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

# Affichage plus agréable
pd.set_option("display.max_columns", None)

# Style des graphiques
sns.set_theme(style="whitegrid")

In [4]:


df = pd.read_csv("../datasets/IMDB-Dataset.csv")

In [9]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
df.shape

(50000, 2)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  str
 1   sentiment  50000 non-null  str
dtypes: str(2)
memory usage: 781.4 KB

In [12]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [13]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [16]:
df.duplicated().sum()

np.int64(418)

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
df.duplicated().sum()

np.int64(0)

In [20]:
df['sentiment'].value_counts()

sentiment
positive    24884
negative    24698
Name: count, dtype: int64

The dataset is highly balanced, with almost an equal distribution between positive and negative reviews. This balance is important because it prevents the analysis or future machine learning models from being biased toward one sentiment class.

In [6]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub("<.*?>", "", text)
    text = re.sub("[^a-zA-Z]", " ", text)
    return text

df['clean_review'] = df['review'].apply(clean_text)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review        50000 non-null  str
 1   sentiment     50000 non-null  str
 2   clean_review  50000 non-null  str
dtypes: str(3)
memory usage: 1.1 MB

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000
)

X = vectorizer.fit_transform(df['clean_review'])

In [12]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [13]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [14]:
from sklearn.linear_model import LogisticRegression


model = LogisticRegression()

model.fit(
    X_train,
    y_train
)

LogisticRegression()

In [18]:
predictions = model.predict(X_test)

In [19]:
from sklearn.naive_bayes import MultinomialNB


model = MultinomialNB()

model.fit(
    X_train,
    y_train
)

MultinomialNB()

In [20]:
from sklearn.metrics import accuracy_score

accuracy_score(
    y_test,
    predictions
)

0.8942

In [21]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        predictions
    )
)

              precision    recall  f1-score   support

           0       0.90      0.88      0.89      4961
           1       0.89      0.91      0.90      5039

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000

The sentiment classification model achieved an accuracy of 89% on the test dataset. The precision and recall scores are balanced across both classes, with an F1-score of 0.89 for negative reviews and 0.90 for positive reviews. This indicates that the model performs consistently and does not show significant bias toward either sentiment category.